### ISSUE TITLE
After installing and transferring REI, execute REI -- an error is reported after version

### ISSUE THREAD

**Issue by coder-chenda** [REI-Network/rei#2]
<img width="1560" alt="image" src="https://user-images.githubusercontent.com/83049018/178155839-5fd8cfbd-acb7-4dac-940f-bbe610bcbdc2.png">

<img width="1391" alt="image" src="https://user-images.githubusercontent.com/83049018/178155854-1587b730-30e5-49d6-86d6-f0f20b5eec9b.png">

**Comment by samlior** [comment]
Is your mac an m1 chip or x86?

**Comment by coder-chenda** [comment]
> Is your mac an m1 chip or x86?

hallo，This is my Mac system. It doesn't seem to be M1
<img width="336" alt="image" src="https://user-images.githubusercontent.com/83049018/178200552-2edf6fde-e8a1-405a-a221-a980f8d8357c.png">

**Comment by samlior** [comment]
This error looks strange, but it seems that there is no problem with your system, you can try to uninstall and install again
```
npm uninstall -g @rei-network/cli
npm install -g @rei-network/cli
```
If it still doesn't work, maybe it can only be [installed from source](https://docs.rei.network/developer/quick-start)

**Comment by samlior** [comment]
Looks like this issue has been resolved
